### ISSUE TITLE
Update "latest" tag

### ISSUE THREAD

**Issue by ale5000-git** [bewuethr/release-tracker-action#5]
Could you please also update the `latest` tag if already exist?

**Comment by bewuethr** [comment]
What should it point to? The latest commit, or the most recent tag? I'm thinking along the lines of how Go select module versions when you use `@latest` (described [here](https://golang.org/ref/mod#version-queries)):

> - The string `latest`, which selects the highest available release version. If there are no release versions, `latest` selects the highest pre-release version. If there no tagged versions, `latest` selects a pseudo-version for the commit at the tip of the repository’s default branch.

For the purposes of this action, I'd do something like

- Point `latest` to most recent commit tagged with a semantic version
- If there are no tagged commits (which would be strange, since the whole point of the action is to move tags around...), then point `latest` to the most recent commit

And I'm thinking of adding this as an option, something like `move-latest: true`, would that work?

**Comment by ale5000-git** [comment]
Thanks for the reply.

I think it make more sense to:
- Point latest to most recent commit tagged with a semantic version
- If there are no tagged commits (which would be strange, since the whole point of the action is to move tags around...), then do nothing
Since to use the latest commit one can already use @main (or @master for legacy repository).
